\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={SLR Example: Album Sales Data},
            pdfauthor={NKN},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\usepackage{longtable,booktabs}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{SLR Example: Album Sales Data}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
    \author{NKN}
    \preauthor{\centering\large\emph}
  \postauthor{\par}
      \predate{\centering\large\emph}
  \postdate{\par}
    \date{January 1, 2018}


\begin{document}
\maketitle

\section{load relevant libraries}\label{load-relevant-libraries}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(readr)}
\KeywordTok{library}\NormalTok{(ggplot2)}
\KeywordTok{library}\NormalTok{(xtable)}
\end{Highlighting}
\end{Shaded}

\section{Read the data}\label{read-the-data}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(knitr)}
\NormalTok{AlbumSales1 <-}\StringTok{ }\KeywordTok{read_csv}\NormalTok{(}\StringTok{"C:/Users/Ali Javed/Desktop/R/GIAN/Data/CSV/AlbumSales1.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Parsed with column specification:
## cols(
##   adverts = col_double(),
##   sales = col_integer()
## )
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{head}\NormalTok{(AlbumSales1)}
\end{Highlighting}
\end{Shaded}

\section{A tibble: 6 x 2}\label{a-tibble-6-x-2}

adverts sales 1 10.3 330 2 986. 120 3 1446. 360 4 1188. 270 5 575. 220 6
569. 170

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{names}\NormalTok{(AlbumSales1)}
\end{Highlighting}
\end{Shaded}

{[}1{]} ``adverts'' ``sales''

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(AlbumSales1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
adverts             sales      
\end{verbatim}

Min. : 9.104 Min. : 10.0\\
1st Qu.: 215.918 1st Qu.:137.5\\
Median : 531.916 Median :200.0\\
Mean : 614.412 Mean :193.2\\
3rd Qu.: 911.226 3rd Qu.:250.0\\
Max. :2271.860 Max. :360.0

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{kable}\NormalTok{(}\KeywordTok{summary}\NormalTok{(AlbumSales1))}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lcc@{}}
\toprule
& adverts & sales\tabularnewline
\midrule
\endhead
& Min. : 9.104 & Min. : 10.0\tabularnewline
& 1st Qu.: 215.918 & 1st Qu.:137.5\tabularnewline
& Median : 531.916 & Median :200.0\tabularnewline
& Mean : 614.412 & Mean :193.2\tabularnewline
& 3rd Qu.: 911.226 & 3rd Qu.:250.0\tabularnewline
& Max. :2271.860 & Max. :360.0\tabularnewline
\bottomrule
\end{longtable}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{print}\NormalTok{(}\KeywordTok{xtable}\NormalTok{(}\KeywordTok{summary}\NormalTok{(AlbumSales1)),}\DataTypeTok{type=}\StringTok{"html"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
adverts </th> <th>     sales </th>  </tr>
\end{verbatim}

X

Min. : 9.104

Min. : 10.0

X.1

1st Qu.: 215.918

1st Qu.:137.5

X.2

Median : 531.916

Median :200.0

X.3

Mean : 614.412

Mean :193.2

X.4

3rd Qu.: 911.226

3rd Qu.:250.0

X.5

Max. :2271.860

Max. :360.0

\section{ScatterPlot}\label{scatterplot}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{attach}\NormalTok{(AlbumSales1)}
\KeywordTok{plot}\NormalTok{(adverts,sales)}
\KeywordTok{title}\NormalTok{(}\StringTok{"Scatterplot of Sales Figures vs Advertisement Expenditure"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{AlbumSalesLinearRegPred_files/figure-latex/unnamed-chunk-3-1.pdf}

\section{Fancy Scatterplot}\label{fancy-scatterplot}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{attach}\NormalTok{(AlbumSales1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## The following objects are masked from AlbumSales1 (pos = 3):
## 
##     adverts, sales
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{scatter <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(AlbumSales1, }\KeywordTok{aes}\NormalTok{(adverts, sales))}
\NormalTok{scatter }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_point}\NormalTok{() }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_smooth}\NormalTok{() }\OperatorTok{+}\StringTok{ }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x =} \StringTok{"Ad Exp"}\NormalTok{, }\DataTypeTok{y =} \StringTok{"Sales"}\NormalTok{) }\OperatorTok{+}\StringTok{ }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"      Scatterplot of Sales Figures vs Advertisement Expenditure"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using method = 'loess' and formula 'y ~ x'
\end{verbatim}

\includegraphics{AlbumSalesLinearRegPred_files/figure-latex/unnamed-chunk-4-1.pdf}

\section{Fancy Scatterplot with the Regression Line
added}\label{fancy-scatterplot-with-the-regression-line-added}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{attach}\NormalTok{(AlbumSales1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## The following objects are masked from AlbumSales1 (pos = 3):
## 
##     adverts, sales
\end{verbatim}

\begin{verbatim}
## The following objects are masked from AlbumSales1 (pos = 4):
## 
##     adverts, sales
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{scatter <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(AlbumSales1, }\KeywordTok{aes}\NormalTok{(adverts, sales))}
\NormalTok{scatter }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_point}\NormalTok{() }\OperatorTok{+}\StringTok{ }
\StringTok{    }\KeywordTok{geom_smooth}\NormalTok{() }\OperatorTok{+}
\StringTok{    }\KeywordTok{geom_smooth}\NormalTok{(}\DataTypeTok{method =} \StringTok{"lm"}\NormalTok{, }\DataTypeTok{colour =} \StringTok{"Red"}\NormalTok{) }\OperatorTok{+}\StringTok{ }
\StringTok{    }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x =} \StringTok{"Ad Exp"}\NormalTok{, }\DataTypeTok{y =} \StringTok{"Sales"}\NormalTok{) }\OperatorTok{+}\StringTok{ }
\StringTok{    }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"      Scatterplot of Sales Figures vs Advertisement Expenditure"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using method = 'loess' and formula 'y ~ x'
\end{verbatim}

\includegraphics{AlbumSalesLinearRegPred_files/figure-latex/unnamed-chunk-5-1.pdf}

\section{Fitting a Simple Linear
Regression}\label{fitting-a-simple-linear-regression}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{AlbumSales.out1 <-}\StringTok{ }\KeywordTok{lm}\NormalTok{(sales }\OperatorTok{~}\StringTok{ }\NormalTok{adverts, }\DataTypeTok{data =}\NormalTok{ AlbumSales1)}
\KeywordTok{summary}\NormalTok{(AlbumSales.out1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = sales ~ adverts, data = AlbumSales1)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -152.949  -43.796   -0.393   37.040  211.866 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept) 1.341e+02  7.537e+00  17.799   <2e-16 ***
## adverts     9.612e-02  9.632e-03   9.979   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 65.99 on 198 degrees of freedom
## Multiple R-squared:  0.3346, Adjusted R-squared:  0.3313 
## F-statistic: 99.59 on 1 and 198 DF,  p-value: < 2.2e-16
\end{verbatim}

\section{What are all these numbers:}\label{what-are-all-these-numbers}

\[ \mbox{Residual Standard Error} = 65.99 = \sqrt{\frac{ \mbox{ Residual Sum of Squares}}{198} } \]

\[ \mbox{Therefore,  RSS=}  198* (65.99)^2 = 198*4354.68=862226.7\]

\[ \mbox{Now, we can find SSTotal from RSS and } R^2: \]
\[0.3346=R^2=1-\frac{RSS}{SST} \implies SST= \frac{RSS}{(1-R^2)}= \frac{862226.7}{1-0.3346}=1295802;  \mbox{   and  SSModel=SST-RSS=}1295802-862227=433575  \]

\[ \mbox{ The F-statistics: } \frac{ \mbox{MSModel} }{ \mbox{MSError}} = \frac{ \mbox{SSModel/DF} }{ \mbox{RSS/DF}} =
\frac{ \mbox{433575/1} }{ \mbox{862227/198}} = 99.59 \]

\section{Compute the p-value for the above
F-statistic}\label{compute-the-p-value-for-the-above-f-statistic}

\section{For small p-values, we can find the upper bound as needed by
some publications as
follows.}\label{for-small-p-values-we-can-find-the-upper-bound-as-needed-by-some-publications-as-follows.}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pvalue <-}\StringTok{ }\DecValTok{1}\OperatorTok{-}\KeywordTok{pf}\NormalTok{(}\FloatTok{99.59}\NormalTok{,}\DecValTok{1}\NormalTok{,}\DecValTok{198}\NormalTok{)}
\KeywordTok{formatC}\NormalTok{(pvalue, }\DataTypeTok{format =} \StringTok{"e"}\NormalTok{, }\DataTypeTok{digits =} \DecValTok{8}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "0.00000000e+00"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{print}\NormalTok{(pvalue)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0
\end{verbatim}

Now, we can construct the traditional ANOVA:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(xtable)}
\NormalTok{tab <-}\StringTok{ }\KeywordTok{xtable}\NormalTok{(}\KeywordTok{summary}\NormalTok{(AlbumSales.out1)}\OperatorTok{$}\NormalTok{coef, }\DataTypeTok{digits=}\KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{))}
\KeywordTok{print}\NormalTok{(tab, }\DataTypeTok{type=}\StringTok{"html"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Estimate

Std. Error

t value

Pr(\textgreater{}\textbar{}t\textbar{})

(Intercept)

134.14

7.54

17.8

0.00

adverts

0.10

0.01

10.0

0.00

Check your results below using R's anova function

\section{Check your results below using R's anova
function}\label{check-your-results-below-using-rs-anova-function}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(AlbumSales.out1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = sales ~ adverts, data = AlbumSales1)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -152.949  -43.796   -0.393   37.040  211.866 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept) 1.341e+02  7.537e+00  17.799   <2e-16 ***
## adverts     9.612e-02  9.632e-03   9.979   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 65.99 on 198 degrees of freedom
## Multiple R-squared:  0.3346, Adjusted R-squared:  0.3313 
## F-statistic: 99.59 on 1 and 198 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{anova}\NormalTok{(AlbumSales.out1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Analysis of Variance Table
## 
## Response: sales
##            Df Sum Sq Mean Sq F value    Pr(>F)    
## adverts     1 433688  433688  99.587 < 2.2e-16 ***
## Residuals 198 862264    4355                      
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\section{Predictions and Confidence Intervals for the conditional
mean}\label{predictions-and-confidence-intervals-for-the-conditional-mean}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{predict}\NormalTok{(AlbumSales.out1,}\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{adverts=}\KeywordTok{c}\NormalTok{(}\DecValTok{100}\NormalTok{)),}\DataTypeTok{interval=}\KeywordTok{c}\NormalTok{(}\StringTok{"prediction"}\NormalTok{),}\DataTypeTok{se.fit=}\OtherTok{TRUE}\NormalTok{)}\OperatorTok{$}\NormalTok{fit[}\DecValTok{1}\NormalTok{,] }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       fit       lwr       upr 
## 143.75239  12.92577 274.57900
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{predict}\NormalTok{(AlbumSales.out1,}\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{adverts=}\KeywordTok{c}\NormalTok{(}\DecValTok{100}\NormalTok{)),}\DataTypeTok{interval=}\KeywordTok{c}\NormalTok{(}\StringTok{"confidence"}\NormalTok{),}\DataTypeTok{se.fit=}\OtherTok{TRUE}\NormalTok{)}\OperatorTok{$}\NormalTok{fit[}\DecValTok{1}\NormalTok{,]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      fit      lwr      upr 
## 143.7524 130.3301 157.1746
\end{verbatim}

\includegraphics{figures/predictionORmeans.png} \$\$

\begin{array}{rl} 
\mbox{Point Prediction:} & \hat{Y} = \hat{\beta_0}+ \hat{\beta_1} x  \\
\mbox{Prediction Interval:}  & \hat{\beta_0}+ \hat{\beta_1} x \pm t_{\alpha/2,n-2} \hat{\sigma} \sqrt{ 1+ \frac{1}{n} + \frac{(x-\bar{X})^2}{S_{XX}} }
\end{array}

\$\$

\[
\begin{array}{rl} 
\mbox{Point Estimate:} & \hat{Y} = \hat{\beta_0}+ \hat{\beta_1} x  \\
\mbox{Interval Estimate:}  & \hat{\beta_0}+ \hat{\beta_1} x \pm t_{\alpha/2,n-2} \hat{\sigma} \sqrt{\frac{1}{n} + \frac{(x-\bar{X})^2}{S_{XX}} }
\end{array}
\] \#Predictions and Confidence Intervals for the conditional mean

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{predict}\NormalTok{(AlbumSales.out1,}\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{adverts=}\KeywordTok{c}\NormalTok{(}\DecValTok{100}\NormalTok{,}\DecValTok{200}\NormalTok{)),}\DataTypeTok{interval=}\KeywordTok{c}\NormalTok{(}\StringTok{"prediction"}\NormalTok{),}\DataTypeTok{se.fit=}\OtherTok{TRUE}\NormalTok{)}\OperatorTok{$}\NormalTok{fit[}\DecValTok{1}\OperatorTok{:}\DecValTok{2}\NormalTok{,] }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        fit      lwr      upr
## 1 143.7524 12.92577 274.5790
## 2 153.3648 22.66636 284.0633
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{predict}\NormalTok{(AlbumSales.out1,}\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{adverts=}\KeywordTok{c}\NormalTok{(}\DecValTok{100}\NormalTok{,}\DecValTok{200}\NormalTok{)),}\DataTypeTok{interval=}\KeywordTok{c}\NormalTok{(}\StringTok{"confidence"}\NormalTok{),}\DataTypeTok{se.fit=}\OtherTok{TRUE}\NormalTok{)}\OperatorTok{$}\NormalTok{fit[}\DecValTok{1}\OperatorTok{:}\DecValTok{2}\NormalTok{,]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        fit      lwr      upr
## 1 143.7524 130.3301 157.1746
## 2 153.3648 141.2552 165.4745
\end{verbatim}


\end{document}
